{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ include "distribution-ui.serviceAccountName" . }}
    labels:
      {{- include "distribution-ui.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
    annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
  {{- end }}
