apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: interface-exception-collector
build:
  artifacts:
  - image: interface-exception-collector
    docker:
      dockerfile: src/main/docker/Dockerfile
    sync:
      manual:
      - src: "target/*.jar"
        dest: /app
deploy:
  kubectl:
    manifests:
    - src/main/k8s/*.yaml
portForward:
- resourceType: service
  resourceName: interface-exception-collector-service
  port: 8080
  localPort: 8080
- resourceType: service
  resourceName: postgres
  port: 5432
  localPort: 5432
- resourceType: service
  resourceName: kafka
  port: 9092
  localPort: 9092