TRUNCATE TABLE receiving.lk_barcode_pattern CASCADE;
TRUNCATE TABLE receiving.lk_barcode_translation CASCADE;

INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value, sixth_digit) VALUES (1, '9500', 'ON', 'V');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value, sixth_digit) VALUES (2, '5100', 'OP', 'V');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value, sixth_digit) VALUES (3, '0600', 'AN', 'V');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value, sixth_digit) VALUES (4, '6200', 'AP', 'V');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value, sixth_digit) VALUES (5, '1700', 'BN', 'V');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value, sixth_digit) VALUES (6, '7300', 'BP', 'V');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value, sixth_digit) VALUES (7, '2800', 'ABN', 'V');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value, sixth_digit) VALUES (8, '8400', 'ABP', 'V');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (9, '5500', 'O');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (10, '6600', 'A');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (11, '7700', 'B');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (12, '8800', 'AB');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (13, 'A000', 'A');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (14, 'B000', 'B');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (15, 'C000', 'AB');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (16, 'D000', 'O');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (17, 'E000', 'P');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (18, 'F000', 'N');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (19, 'G000', 'N/A');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (20, 'H000', 'N/A');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (21, '9100', 'ON');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (22, '4700', 'OP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (23, '0200', 'AN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (24, '5800', 'AP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (25, '1300', 'BN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (26, '6900', 'BP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (27, '2400', 'ABN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (28, '8000', 'ABP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (29, 'P200', 'O');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (30, 'A200', 'A');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (31, 'B200', 'B');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (32, 'C200', 'AB');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (33, '9200', 'ON');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (34, '4800', 'OP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (35, '0300', 'AN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (36, '5900', 'AP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (37, '1400', 'BN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (38, '7000', 'BP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (39, '2500', 'ABN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (40, '8100', 'ABP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (41, 'P300', 'O');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (42, 'A300', 'A');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (43, 'B300', 'B');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (44, 'C300', 'AB');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (45, '9300', 'ON');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (46, '4900', 'OP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (47, '0400', 'AN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (48, '6000', 'AP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (49, '1500', 'BN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (50, '7100', 'BP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (51, '2600', 'ABN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (52, '8200', 'ABP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (53, 'P400', 'O');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (54, 'A400', 'A');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (55, 'B400', 'B');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (56, 'C400', 'AB');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (57, '9400', 'ON');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (58, '5000', 'OP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (59, '0500', 'AN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (60, '6100', 'AP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (61, '1600', 'BN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (62, '7200', 'BP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (63, '2700', 'ABN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (64, '8300', 'ABP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (65, 'P500', 'O');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (66, 'A500', 'A');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (67, 'B500', 'B');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (68, 'C500', 'AB');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (69, '9600', 'ON');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (70, '5200', 'OP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (71, '0700', 'AN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (72, '6300', 'AP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (73, '1800', 'BN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (74, '7400', 'BP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (75, '2900', 'ABN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (76, '8500', 'ABP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (77, 'P700', 'O');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (78, 'A700', 'A');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (79, 'B700', 'B');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (80, 'C700', 'AB');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (81, '9700', 'ON');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (82, '5300', 'OP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (83, '0800', 'AN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (84, '6400', 'AP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (85, '1900', 'BN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (86, '7500', 'BP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (87, '3000', 'ABN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (88, '8600', 'ABP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (89, 'P800', 'O');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (90, 'A800', 'A');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (91, 'B800', 'B');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (92, 'C800', 'AB');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (93, '9800', 'ON');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (94, '5400', 'OP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (95, '0900', 'AN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (96, '6500', 'AP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (97, '2000', 'BN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (98, '7600', 'BP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (99, '3100', 'ABN');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (100, '8700', 'ABP');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (101, 'P900', 'O');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (102, 'A900', 'A');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (103, 'B900', 'B');
INSERT INTO receiving.lk_barcode_translation (id, from_value, to_value) VALUES (104, 'C900', 'AB');

INSERT INTO receiving.lk_barcode_pattern (id, pattern, match_groups, parse_type) VALUES (1, '(\=)([A-Z]{1}\w{12})(00)', 2, 'BARCODE_UNIT_NUMBER');
INSERT INTO receiving.lk_barcode_pattern (id, pattern, match_groups, parse_type) VALUES (2, '(\=\%)(\w{4})', 2, 'BARCODE_BLOOD_GROUP');
INSERT INTO receiving.lk_barcode_pattern (id, pattern, match_groups, parse_type) VALUES (3, '(\=\<)(\w{8})', 2, 'BARCODE_PRODUCT_CODE');
INSERT INTO receiving.lk_barcode_pattern (id, pattern, match_groups, parse_type) VALUES (4, '(\&\>)(\d{3}\d{3}\d{2}\d{2})', 2, 'BARCODE_EXPIRATION_DATE');