apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: caching
  labels:
    app: redis
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          args: [--maxmemory, 192mb, --maxmemory-policy, allkeys-lfu, --activedefrag, "yes"]
          ports:
            - containerPort: 6379
