apiVersion: v1
kind: Secret
metadata:
  name: {{ include "interface-exception-collector.fullname" . }}-app-secret
  labels:
    {{- include "interface-exception-collector.labels" . | nindent 4 }}
    component: configuration
type: Opaque
data:
  # Database credentials
  DB_PASSWORD: {{ .Values.database.password | b64enc }}
  
  # Redis credentials
  {{- if .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
  {{- end }}
  
  # JWT secret
  JWT_SECRET: {{ .Values.security.jwt.secret | b64enc }}
  
  # External service API keys
  ORDER_SERVICE_API_KEY: {{ .Values.externalServices.order.apiKey | b64enc }}
  COLLECTION_SERVICE_API_KEY: {{ .Values.externalServices.collection.apiKey | b64enc }}
  DISTRIBUTION_SERVICE_API_KEY: {{ .Values.externalServices.distribution.apiKey | b64enc }}
  
  # Kafka SSL passwords (if SSL is enabled)
  {{- if .Values.kafka.ssl.enabled }}
  KAFKA_SSL_TRUSTSTORE_PASSWORD: {{ .Values.kafka.ssl.truststorePassword | b64enc }}
  KAFKA_SSL_KEYSTORE_PASSWORD: {{ .Values.kafka.ssl.keystorePassword | b64enc }}
  KAFKA_SSL_KEY_PASSWORD: {{ .Values.kafka.ssl.keyPassword | b64enc }}
  {{- end }}
  
  # TLS keystore passwords (if TLS is enabled)
  {{- if .Values.server.ssl.enabled }}
  SERVER_SSL_KEYSTORE_PASSWORD: {{ .Values.server.ssl.keystorePassword | b64enc }}
  SERVER_SSL_TRUSTSTORE_PASSWORD: {{ .Values.server.ssl.truststorePassword | b64enc }}
  {{- end }}
  
  # TLS application keystore passwords (if application TLS is enabled)
  {{- if .Values.security.tls.enabled }}
  TLS_KEYSTORE_PASSWORD: {{ .Values.security.tls.keystorePassword | b64enc }}
  TLS_TRUSTSTORE_PASSWORD: {{ .Values.security.tls.truststorePassword | b64enc }}
  {{- end }}

---
{{- if .Values.kafka.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "interface-exception-collector.fullname" . }}-kafka-ssl
  labels:
    {{- include "interface-exception-collector.labels" . | nindent 4 }}
    component: kafka-ssl
type: Opaque
data:
  truststore.jks: {{ .Values.kafka.ssl.truststore | b64enc }}
  keystore.jks: {{ .Values.kafka.ssl.keystore | b64enc }}
{{- end }}

---
{{- if .Values.server.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "interface-exception-collector.fullname" . }}-server-ssl
  labels:
    {{- include "interface-exception-collector.labels" . | nindent 4 }}
    component: server-ssl
type: Opaque
data:
  keystore.jks: {{ .Values.server.ssl.keystore | b64enc }}
  {{- if .Values.server.ssl.truststore }}
  truststore.jks: {{ .Values.server.ssl.truststore | b64enc }}
  {{- end }}
{{- end }}

---
{{- if .Values.security.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "interface-exception-collector.fullname" . }}-app-tls
  labels:
    {{- include "interface-exception-collector.labels" . | nindent 4 }}
    component: app-tls
type: Opaque
data:
  keystore.jks: {{ .Values.security.tls.keystore | b64enc }}
  {{- if .Values.security.tls.truststore }}
  truststore.jks: {{ .Values.security.tls.truststore | b64enc }}
  {{- end }}
{{- end }}