openapi: 3.0.0
info:
  description: "Order Management API to accept a create of an order from a customer"
  version: "1.0.0"
  title: "Order Management Interface API"
  contact:
    url: 'https://arc-one.com'
    email: development@arc-one.com
    name: Development Team
tags:
- name: "order"
  description: "Order inbound data"
security:
  - bearerAuth: []
paths:
  /orders:
    post:
      tags:
        - "order"
      summary: "Receives an order data to be created"
      description: <p>Create an order.</p>
      operationId: "createOrder"
      requestBody:
        content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Order"
        required: true
      responses:
        "200":
          description: "successful operation"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ResponseStatus"
        "405":
          description: "Invalid JSON format"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Unauthorized"
      security:
        - bearerAuth: []
components:
  schemas:
    Order:
      type: "object"
      required:
      - "externalId"
      - "locationCode"
      properties:
        externalId:
          type: "string"
          maxLength: 50
          minLength: 1
          example: "11411792"
        orderStatus:
          type: "string"
          example: "OPEN"
        locationCode:
          type: "string"
          maxLength: 50
          minLength: 1
          example: "2265"
        createDate:
          $ref: "#/components/schemas/dateTimePattern"
        createEmployeeCode:
          type: string
          example: 1123g
        shipmentType:
          type: string
          example: CUSTOMER
        deliveryType:
          type: string
          example: "SCHEDULED"
        orderPickType:
          $ref:  "#/components/schemas/OrderPickType"
        shippingMethod:
          type: "string"
          example: "FEDEX"
        productCategory:
          type: "string"
          example: "FROZEN"
        desiredShippingDate:
          $ref: '#/components/schemas/datePattern'
        shippingCustomerCode:
          type: "string"
          maxLength: 500
          minLength: 0
          example: "049T1830TB"
        billingCustomerCode:
          type: "string"
          maxLength: 100
          minLength: 0
          example: "049T1830TA"
        comments:
          type: "string"
          maxLength: 1000
          minLength: 0
        orderItems:
          type: "array"
          minItems: 1
          items:
            $ref: "#/components/schemas/OrderItem"
      xml:
        name: "Order"
    datePattern:
      type: string
      pattern: "^(\\d{4}-\\d{2}-\\d{2})$"
      example: "2020-06-12"
    dateTimePattern:
      type: string
      pattern: "^(\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2})$"
    OrderPickType:
      type: "object"
      properties:
        willCallPickUp:
          type: "boolean"
          example: true
        phoneNumber:
          type: "string"
          maxLength: 255
          minLength: 0
          example: "1112332233"
    OrderItem:
      type: "object"
      properties:
        productFamily:
          type: "string"
          example: "APHERESIS_PLASMA"
        bloodType:
          type: "string"
          example: "AB"
        quantity:
          type: "integer"
          example: 3
        comments:
          type: "string"
    ResponseStatus:
      type: "object"
      properties:
        status:
          type: "string"
        id:
          type: "string"
        errorMessage:
          type: "string"
        timestamp:
          type: "string"
      xml:
        name: "ResponseStatus"
    Unauthorized:
        title: DocumentResponse
        type: object
        example:
          {
            "type": "https://arc-one.com/problem/problem-with-message",
            "title": "Unauthorized",
            "status": 401,
            "detail": "Full authentication is required to access this resource",
            "path": "/v1/orders",
            "message": "error.http.401"
          }
        properties:
          type:
            type: string
          title:
            type: string
          status:
            type: integer
          detail:
            type: string
          path:
            type: string
          message:
            type: string
  securitySchemes:
    bearerAuth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://id.dev.ao.arc-one.com/auth/realms/rsa/protocol/openid-connect/auth'
          scopes:
            openid: OpenID scope
  responses: {}
