apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: db
type: Opaque
stringData:
  url: "postgres://biopro:pass@postgresql-service.db.svc.cluster.local:5432/biopro?sslmode=disable"
  password: biopro-password
