apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: postgres-migration
  namespace: db
spec:
  urlFrom:
    secretKeyRef:
      key: url
      name: postgres-credentials
  schema:
    configMapKeyRef:
      key: schema.sql
      name: biopro-migration
  policy:
    diff:
      skip:
        drop_schema: true
    lint:
      destructive:
        error: false
