kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-external-deployment
  namespace: queue
  labels:
    app: kafka-external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-external
  template:
    metadata:
      labels:
        app: kafka-external
    spec:
      containers:
        - name: kafka-ext
          image: confluentinc/cp-kafka:7.6.1
          ports:
            - containerPort: 29093
          env:
            - name: CLUSTER_ID
              value: "2"
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:29093,PLAINTEXT_INTERNAL://:9093"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://localhost:29093,PLAINTEXT_INTERNAL://kafka-external-service.queue.svc.cluster.local:9093"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT_INTERNAL"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "1"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
