kind: Deployment
apiVersion: apps/v1
metadata:
  name: redpanda-console-deployment
  namespace: queue
  labels:
    app: redpanda-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
        - name: redpanda-console
          image: redpandadata/console:v2.5.2
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              value: "kafka-service.queue.svc.cluster.local:9092,kafka-external-service.queue.svc.cluster.local:9093"
