{{ if .Values.flyway.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "api.fullname" . }}-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: flyway
          image: "{{ .Values.image.repository }}/{{ .Values.environment }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: [ "/flyway/flyway" ]  # Overrides the default entrypoint
          args:
              - info
              - repair
              - migrate
              - info
          env:
            {{- toYaml .Values.flyway.env | nindent 12 }}
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      restartPolicy: Never
  {{- end }}
