apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topics-job
  labels:
    app: kafka-topics-job
spec:
  template:
    metadata:
      labels:
        app: kafka-topics-job
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-kafka
        image: confluentinc/cp-kafka:7.4.0
        command:
          - sh
          - -c
          - |
            until kafka-topics --bootstrap-server kafka:9092 --list; do
              echo "Waiting for Kafka to be ready..."
              sleep 5
            done
            echo "Kafka is ready!"
      containers:
      - name: create-topics
        image: confluentinc/cp-kafka:7.4.0
        command:
          - sh
          - -c
          - |
            # Function to create topic if it doesn't exist
            create_topic_if_not_exists() {
              local topic_name=$1
              local partitions=${2:-3}
              local replication_factor=${3:-1}
              
              if kafka-topics --bootstrap-server kafka:9092 --list | grep -q "^${topic_name}$"; then
                echo "Topic ${topic_name} already exists"
              else
                echo "Creating topic ${topic_name}"
                kafka-topics --bootstrap-server kafka:9092 \
                  --create \
                  --topic ${topic_name} \
                  --partitions ${partitions} \
                  --replication-factor ${replication_factor}
                echo "Topic ${topic_name} created successfully"
              fi
            }

            # Create inbound topics (from interface services)
            create_topic_if_not_exists "OrderRejected" 3 1
            create_topic_if_not_exists "OrderCancelled" 3 1
            create_topic_if_not_exists "CollectionRejected" 3 1
            create_topic_if_not_exists "DistributionFailed" 3 1
            create_topic_if_not_exists "ValidationError" 3 1

            # Create outbound topics (from exception collector)
            create_topic_if_not_exists "ExceptionCaptured" 3 1
            create_topic_if_not_exists "ExceptionResolved" 3 1
            create_topic_if_not_exists "ExceptionRetryCompleted" 3 1
            create_topic_if_not_exists "CriticalExceptionAlert" 3 1

            # Create dead letter topics
            create_topic_if_not_exists "OrderRejected.DLT" 1 1
            create_topic_if_not_exists "OrderCancelled.DLT" 1 1
            create_topic_if_not_exists "CollectionRejected.DLT" 1 1
            create_topic_if_not_exists "DistributionFailed.DLT" 1 1
            create_topic_if_not_exists "ValidationError.DLT" 1 1

            echo "All Kafka topics created successfully!"
            
            # List all topics for verification
            echo "Current topics:"
            kafka-topics --bootstrap-server kafka:9092 --list
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"