apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-rsocket-server
  labels:
    app: mock-rsocket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-rsocket-server
  template:
    metadata:
      labels:
        app: mock-rsocket-server
    spec:
      containers:
      - name: mock-rsocket-server
        image: artifactory.sha.ao.arc-one.com/docker/biopro/utils/rsocket_mock:21.0.1
        ports:
        - containerPort: 7000
          name: rsocket
        volumeMounts:
        - name: mappings
          mountPath: /app/mappings
          readOnly: true
        - name: responses
          mountPath: /app/__files
          readOnly: true
        env:
        - name: SERVER_PORT
          value: "7000"
        - name: MAPPINGS_PATH
          value: "/app/mappings"
        - name: RESPONSES_PATH
          value: "/app/__files"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
      volumes:
      - name: mappings
        configMap:
          name: mock-rsocket-mappings
      - name: responses
        configMap:
          name: mock-rsocket-responses
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mock-rsocket-server
  labels:
    app: mock-rsocket-server
spec:
  selector:
    app: mock-rsocket-server
  ports:
  - port: 7000
    targetPort: 7000
    protocol: TCP
    name: rsocket
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mock-rsocket-mappings
data:
  order-success-mapping.json: |
    {
      "request": {
        "routePathPattern": "orders\\.([A-Z0-9-]+)"
      },
      "response": {
        "status": 200,
        "bodyFileName": "orders/complete-order-with-items.json",
        "headers": {
          "Content-Type": "application/json"
        }
      }
    }
  order-not-found-mapping.json: |
    {
      "request": {
        "routePathPattern": "orders\\.(NOTFOUND-.*)"
      },
      "response": {
        "status": 404,
        "bodyFileName": "errors/not-found.json",
        "headers": {
          "Content-Type": "application/json"
        }
      }
    }
  default-fallback-mapping.json: |
    {
      "request": {
        "routePathPattern": ".*"
      },
      "response": {
        "status": 404,
        "jsonBody": {
          "error": "Endpoint not found",
          "message": "The requested route was not found in mock server mappings"
        },
        "headers": {
          "Content-Type": "application/json"
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mock-rsocket-responses
data:
  orders/complete-order-with-items.json: |
    {
      "externalId": "TEST-ORDER-1",
      "customerId": "CUST001",
      "locationCode": "LOC001",
      "orderDate": "2025-01-15T10:30:00Z",
      "status": "PENDING",
      "totalAmount": 1250.00,
      "currency": "USD",
      "orderItems": [
        {
          "itemId": "ITEM001",
          "productCode": "PROD-ABC123",
          "bloodType": "O_POS",
          "productFamily": "RED_BLOOD_CELLS",
          "quantity": 2,
          "unitPrice": 500.00,
          "totalPrice": 1000.00,
          "attributes": {
            "expirationDate": "2025-02-15",
            "donorId": "DONOR123"
          }
        },
        {
          "itemId": "ITEM002",
          "productCode": "PROD-XYZ789",
          "bloodType": "A_NEG",
          "productFamily": "PLATELETS",
          "quantity": 1,
          "unitPrice": 250.00,
          "totalPrice": 250.00,
          "attributes": {
            "expirationDate": "2025-01-20",
            "donorId": "DONOR456"
          }
        }
      ],
      "customerInfo": {
        "name": "Test Customer Hospital",
        "email": "orders@testcustomer.com",
        "phone": "+1-555-0123",
        "contactPerson": "Dr. Jane Smith"
      },
      "shippingAddress": {
        "street": "123 Hospital Drive",
        "city": "Medical City",
        "state": "TX",
        "zipCode": "12345",
        "country": "US",
        "deliveryInstructions": "Deliver to Blood Bank - Building A"
      },
      "metadata": {
        "priority": "URGENT",
        "deliveryDate": "2025-01-16T08:00:00Z",
        "specialHandling": true,
        "temperatureControlled": true
      }
    }
  errors/not-found.json: |
    {
      "error": "ORDER_NOT_FOUND",
      "message": "Order with the specified externalId was not found",
      "timestamp": "2025-01-15T10:30:00Z",
      "details": {
        "errorCode": "ORD_404",
        "retryable": false
      }
    }