apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-rsocket-server
  labels:
    app: mock-rsocket-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: mock-rsocket-server
  template:
    metadata:
      labels:
        app: mock-rsocket-server
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: mock-rsocket-server
        image: artifactory.sha.ao.arc-one.com/docker/biopro/utils/rsocket_mock:21.0.1
        ports:
        - containerPort: 7000
          name: rsocket
        env:
        - name: SERVER_PORT
          value: "7000"
        - name: LOG_LEVEL
          value: "INFO"
        - name: STARTUP_TIMEOUT
          value: "10"
        - name: QUICK_START
          value: "true"
        - name: EMBEDDED_MODE
          value: "true"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 2

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mock-rsocket-server
  labels:
    app: mock-rsocket-server
spec:
  selector:
    app: mock-rsocket-server
  ports:
  - port: 7000
    targetPort: 7000
    protocol: TCP
    name: rsocket
  type: ClusterIP
