apiVersion: v1
kind: ConfigMap
metadata:
  name: partner-order-postgres-config
data:
  POSTGRES_DB: partner_order_db
  POSTGRES_USER: partner_order_user
  POSTGRES_PASSWORD: partner_order_pass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: partner-order-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: partner-order-postgres
  labels:
    app: partner-order-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partner-order-postgres
  template:
    metadata:
      labels:
        app: partner-order-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: partner-order-postgres-config
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - partner_order_user
              - -d
              - partner_order_db
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - partner_order_user
              - -d
              - partner_order_db
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: partner-order-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: partner-order-postgres
  labels:
    app: partner-order-postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: partner-order-postgres