# Feature Unit Number reference: W036825014000
@api @LAB-116 @AOA-75 @LAB-185 @LAB-254 @LAB-379 @LAB-408
Feature: Validate Inventory

    Scenario Outline: Validate Inventory
        Given I have the following inventories:
            | Unit Number   | Product Code | Location   | Status    | Collection Location | Collection TimeZone | Is Labeled | Expires In Days | Quarantine Reasons                                     | Discard Reason           | Unsuitable Reason | Comments                  | Volumes                          |
            | W036825014001 | E0869V00     | LOCATION_1 | AVAILABLE | LOCATION_1          | America/New_York    | true       | 5               |                                                        |                          |                   |                           | Anticoagulant - 50, Volume - 500 |
            | W036825014002 | E0869VA0     | LOCATION_2 | AVAILABLE | LOCATION_2          | America/Los_Angeles | true       | 5               |                                                        |                          |                   |                           |                                  |
            | W036825014003 | E0869VB0     | LOCATION_2 | AVAILABLE | LOCATION_2          | America/Los_Angeles | true       | 5               | ABS_POSITIVE, PENDING_FURTHER_REVIEW_INSPECTION, OTHER |                          |                   | Quarantine other comments |                                  |
            | W036825014004 | E0869VC0     | LOCATION_1 | AVAILABLE | LOCATION_1          | America/New_York    | true       | -1              |                                                        |                          |                   |                           |                                  |
            | W036825014005 | E0869VD0     | LOCATION_1 | DISCARDED | LOCATION_1          | America/New_York    | true       | 5               |                                                        | ADDITIVE_SOLUTION_ISSUES |                   |                           |                                  |
            | W036825014006 | E0869VD0     | LOCATION_1 | AVAILABLE | LOCATION_1          | America/New_York    | true       | 1               |                                                        |                          | ACTIVE_DEFERRAL   |                           |                                  |
            | W036825014006 | E1624V00     | LOCATION_1 | AVAILABLE | LOCATION_1          | America/New_York    | true       | 1               |                                                        |                          | TIMING_RULES      |                           |                                  |
            | W036825014007 | E0869VD0     | LOCATION_1 | DISCARDED | LOCATION_1          | America/New_York    | true       | 5               |                                                        | OTHER                    |                   | Some comments             |                                  |
            | W036825014008 | E0869VD0     | LOCATION_1 | AVAILABLE | LOCATION_1          | America/New_York    | false      | 5               |                                                        |                          |                   |                           |                                  |
            | W036825014009 | E0869VD0     | LOCATION_1 | PACKED    | LOCATION_1          | America/New_York    | true       | 5               |                                                        |                          |                   |                           |                                  |
            | W036825014010 | E0869VD0     | LOCATION_1 | SHIPPED   | LOCATION_1          | America/New_York    | true       | 5               |                                                        |                          |                   |                           |                                  |
        When I request "<Unit Number>" with "<Product Code>" in the "<Location>"
        Then I receive the following:
            | Unit Number   | Product Code   | Temperature Category   | Location   | Collection Location   | Collection TimeZone   | Volumes   | RESPONSE ERROR   | ACTION   | REASON   | MESSAGE   | DETAILS   |
            | <Unit Number> | <Product Code> | <Temperature Category> | <Location> | <Collection Location> | <Collection TimeZone> | <Volumes> | <RESPONSE ERROR> | <ACTION> | <REASON> | <MESSAGE> | <DETAILS> |

        Examples:
            | Unit Number   | Product Code | Temperature Category | Location   | Volumes                          | Collection Location | Collection TimeZone | RESPONSE ERROR                  | ACTION             | REASON          | MESSAGE                                                                                                              | DETAILS                                                                             |
            | W036825014001 | E0869V00     | FROZEN               | LOCATION_1 | Anticoagulant - 50, Volume - 500 | LOCATION_1          | America/New_York    |                                 |                    |                 |                                                                                                                      |                                                                                     |
            | W036825014002 | E0869VA0     | FROZEN               | LOCATION_2 |                                  | LOCATION_2          | America/Los_Angeles |                                 |                    |                 |                                                                                                                      |                                                                                     |
            | W036825014003 | E0869VB0     | FROZEN               | LOCATION_2 |                                  | LOCATION_2          | America/Los_Angeles | INVENTORY_IS_QUARANTINED        | BACK_TO_STORAGE    | BACK_TO_STORAGE | This product is currently in quarantine and needs to be returned to storage.                                         | ABS POSITIVE, PENDING FURTHER REVIEW / INSPECTION, OTHER: Quarantine other comments |
            | W036825014003 | E0869VB0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/Los_Angeles | INVENTORY_NOT_FOUND_IN_LOCATION | BACK_TO_STORAGE    | BACK_TO_STORAGE | This product is not in this location and cannot be shipped.                                                          |                                                                                     |
            | W036825014004 | E0869VC0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_EXPIRED            | TRIGGER_DISCARD    | EXPIRED         | This product is expired and has been discarded. Place in biohazard container.                                        |                                                                                     |
            | W036825014001 | E0869V00     | FROZEN               | LOCATION_2 |                                  | LOCATION_2          | America/New_York    | INVENTORY_NOT_FOUND_IN_LOCATION | BACK_TO_STORAGE    |                 | This product is not in this location and cannot be shipped.                                                          |                                                                                     |
            | W036825014005 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_DISCARDED          | PLACE_IN_BIOHAZARD |                 | This product has already been discarded for Additive Solution Issues in the system. Place in biohazard container.    |                                                                                     |
            | W036825014006 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_UNSUITABLE         | TRIGGER_DISCARD    | ACTIVE_DEFERRAL | This product has an active deferral with a discard consequence and has been discarded. Place in biohazard container. |                                                                                     |
            | W036825014006 | E1624V00     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_UNSUITABLE         | TRIGGER_DISCARD    | TIMING_RULES    | This product has been discarded for Timing Rules. Place in biohazard container.                                      |                                                                                     |
            | W036825014007 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_DISCARDED          | PLACE_IN_BIOHAZARD |                 | This product has already been discarded for OTHER: Some comments in the system. Place in biohazard container.        |                                                                                     |
            | W036825014008 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_UNLABELED          | BACK_TO_STORAGE    |                 | This product is not labeled and cannot be shipped.                                                                   |                                                                                     |
            | W036825014009 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_PACKED             | BACK_TO_STORAGE    |                 | This product is part of a carton and cannot be added.                                                                |                                                                                     |
            | W036825014010 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_SHIPPED            | BACK_TO_STORAGE    |                 | This product was previously shipped.                                                                                 |                                                                                     |

