# Feature Unit Number reference: W777725014000
@api @LAB-116 @AOA-75 @LAB-185 @LAB-254 @LAB-379 @LAB-408 @LAB-518 @validateInventory
Feature: Validate Inventory

    Scenario Outline: Validate Inventory
        Given I have the following inventories:
            | Unit Number   | Product Code | Location   | Status     | Collection Location | Collection TimeZone | Is Labeled | Expires In Days | Quarantine Reasons                                     | Discard Reason           | Unsuitable Reason | Comments                  | Volumes                          |
            | W777725014001 | E0869V00     | LOCATION_1 | AVAILABLE  | LOCATION_1          | America/New_York    | true       | 5               |                                                        |                          |                   |                           | Anticoagulant - 50, Volume - 500 |
            | W777725014002 | E0869VA0     | LOCATION_2 | AVAILABLE  | LOCATION_2          | America/Los_Angeles | true       | 5               |                                                        |                          |                   |                           |                                  |
            | W777725014003 | E0869VB0     | LOCATION_2 | AVAILABLE  | LOCATION_2          | America/Los_Angeles | true       | 5               | ABS_POSITIVE, PENDING_FURTHER_REVIEW_INSPECTION, OTHER |                          |                   | Quarantine other comments |                                  |
            | W777725014004 | E0869VC0     | LOCATION_1 | AVAILABLE  | LOCATION_1          | America/New_York    | true       | -1              |                                                        |                          |                   |                           |                                  |
            | W777725014005 | E0869VD0     | LOCATION_1 | DISCARDED  | LOCATION_1          | America/New_York    | true       | 5               |                                                        | ADDITIVE_SOLUTION_ISSUES |                   |                           |                                  |
            | W777725014006 | E0869VD0     | LOCATION_1 | AVAILABLE  | LOCATION_1          | America/New_York    | true       | 1               |                                                        |                          | ACTIVE_DEFERRAL   |                           |                                  |
            | W777725014006 | E1624V00     | LOCATION_1 | AVAILABLE  | LOCATION_1          | America/New_York    | true       | 1               |                                                        |                          | TIMING_RULES      |                           |                                  |
            | W777725014007 | E0869VD0     | LOCATION_1 | DISCARDED  | LOCATION_1          | America/New_York    | true       | 5               |                                                        | OTHER                    |                   | Some comments             |                                  |
            | W777725014008 | E0869VD0     | LOCATION_1 | AVAILABLE  | LOCATION_1          | America/New_York    | false      | 5               |                                                        |                          |                   |                           |                                  |
            | W777725014009 | E0869VD0     | LOCATION_1 | PACKED     | LOCATION_1          | America/New_York    | true       | 5               |                                                        |                          |                   |                           |                                  |
            | W777725014010 | E0869VD0     | LOCATION_1 | SHIPPED    | LOCATION_1          | America/New_York    | true       | 5               |                                                        |                          |                   |                           |                                  |
            | W777725014011 | E0869VD0     | LOCATION_1 | AVAILABLE  | LOCATION_1          | America/New_York    | true       | -1              |                                                        |                          |                   |                           |                                  |
            | W777725014013 | E0869VD0     | LOCATION_1 | CONVERTED  | LOCATION_1          | America/New_York    | true       | 5               |                                                        |                          |                   |                           |                                  |
            | W777725014014 | E0869VD0     | LOCATION_1 | MODIFIED   | LOCATION_1          | America/New_York    | true       | 5               |                                                        |                          |                   |                           |                                  |
            | W777725014015 | E0869VD0     | LOCATION_1 | IN_TRANSIT | LOCATION_1          | America/New_York    | true       | 5               |                                                        |                          |                   |                           |                                  |



        When I request "<Unit Number>" with "<Product Code>" in the "<Location>"
        Then I receive the following:
            | Unit Number   | Product Code   | Temperature Category   | Location   | Collection Location   | Collection TimeZone   | Volumes   | RESPONSE ERROR   | ACTION   | REASON   | MESSAGE   | DETAILS   |
            | <Unit Number> | <Product Code> | <Temperature Category> | <Location> | <Collection Location> | <Collection TimeZone> | <Volumes> | <RESPONSE ERROR> | <ACTION> | <REASON> | <MESSAGE> | <DETAILS> |

        Examples:
            | Unit Number   | Product Code | Temperature Category | Location   | Volumes                          | Collection Location | Collection TimeZone | RESPONSE ERROR                  | ACTION             | REASON          | MESSAGE                                                                                                              | DETAILS                                                                             |
            | W777725014001 | E0869V00     | FROZEN               | LOCATION_1 | Anticoagulant - 50, Volume - 500 | LOCATION_1          | America/New_York    |                                 |                    |                 |                                                                                                                      |                                                                                     |
            | W777725014002 | E0869VA0     | FROZEN               | LOCATION_2 |                                  | LOCATION_2          | America/Los_Angeles |                                 |                    |                 |                                                                                                                      |                                                                                     |
            | W777725014003 | E0869VB0     | FROZEN               | LOCATION_2 |                                  | LOCATION_2          | America/Los_Angeles | INVENTORY_IS_QUARANTINED        | BACK_TO_STORAGE    | BACK_TO_STORAGE | This product is currently in quarantine and needs to be returned to storage.                                         | ABS POSITIVE, PENDING FURTHER REVIEW / INSPECTION, OTHER: Quarantine other comments |
            | W777725014003 | E0869VB0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/Los_Angeles | INVENTORY_NOT_FOUND_IN_LOCATION | BACK_TO_STORAGE    | BACK_TO_STORAGE | This product is not in this location and cannot be shipped.                                                          |                                                                                     |
            | W777725014004 | E0869VC0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_EXPIRED            | TRIGGER_DISCARD    | EXPIRED         | This product is expired and has been discarded. Place in biohazard container.                                        |                                                                                     |
            | W777725014001 | E0869V00     | FROZEN               | LOCATION_2 |                                  | LOCATION_2          | America/New_York    | INVENTORY_NOT_FOUND_IN_LOCATION | BACK_TO_STORAGE    |                 | This product is not in this location and cannot be shipped.                                                          |                                                                                     |
            | W777725014005 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_DISCARDED          | PLACE_IN_BIOHAZARD |                 | This product has already been discarded for Additive Solution Issues in the system. Place in biohazard container.    |                                                                                     |
            | W777725014006 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_UNSUITABLE         | TRIGGER_DISCARD    | ACTIVE_DEFERRAL | This product has an active deferral with a discard consequence and has been discarded. Place in biohazard container. |                                                                                     |
            | W777725014006 | E1624V00     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_UNSUITABLE         | TRIGGER_DISCARD    | TIMING_RULES    | This product has been discarded for Timing Rules. Place in biohazard container.                                      |                                                                                     |
            | W777725014007 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_DISCARDED          | PLACE_IN_BIOHAZARD |                 | This product has already been discarded for OTHER: Some comments in the system. Place in biohazard container.        |                                                                                     |
            | W777725014008 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_UNLABELED          | BACK_TO_STORAGE    |                 | This product is not labeled and cannot be shipped.                                                                   |                                                                                     |
            | W777725014009 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_PACKED             | BACK_TO_STORAGE    |                 | This product is part of a carton and cannot be added.                                                                |                                                                                     |
            | W777725014010 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_SHIPPED            | BACK_TO_STORAGE    |                 | This product was previously shipped.                                                                                 |                                                                                     |
            | W777725014011 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_EXPIRED            | TRIGGER_DISCARD    |                 | This product is expired and has been discarded. Place in biohazard container.                                        |                                                                                     |
            | W777725014013 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_CONVERTED          | BACK_TO_STORAGE    |                 | This product is converted and cannot be used.                                                                        |                                                                                     |
            | W777725014014 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_MODIFIED           | BACK_TO_STORAGE    |                 | This product is modified and cannot be used.                                                                         |                                                                                     |
            | W777725014015 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_IN_TRANSIT         | BACK_TO_STORAGE    |                 | This product is in transit and cannot be used.                                                                       |                                                                                     |


    @api @MGF1-288 @MGF1-290 @validateInventory
    Scenario Outline: Validate Inventory by Unit Number
        Given I have the following inventories:
            | Unit Number   | Product Code | Location   | Status    | Collection Location | Collection TimeZone | Is Labeled | Expires In Days | Quarantine Reasons                                     | Discard Reason           | Unsuitable Reason | Comments                  | Volumes                          | Storage Location | Device Stored | Properties  |
            | W777725014012 | E0869V00     | LOCATION_1 | AVAILABLE | LOCATION_1          | America/New_York    | true       | 5               |                                                        |                          |                   |                           | Anticoagulant - 50, Volume - 500 | Freezer 1        | MDL SHELF 100 | COMPLETED=Y |
            | W777725014012 | E0869VA0     | LOCATION_2 | AVAILABLE | LOCATION_2          | America/Los_Angeles | true       | 5               |                                                        |                          |                   |                           |                                  | Freezer 2        |               |             |
            | W777725014012 | E0869VB0     | LOCATION_1 | AVAILABLE | LOCATION_2          | America/Los_Angeles | false      | 5               | ABS_POSITIVE, PENDING_FURTHER_REVIEW_INSPECTION, OTHER |                          |                   | Quarantine other comments |                                  | Refrigerator 1   | MDL SHELF 100 |             |
            | W777725014012 | E0869VC0     | LOCATION_1 | AVAILABLE | LOCATION_1          | America/New_York    | true       | -1              |                                                        |                          |                   |                           |                                  | Refrigerator 2   |               |             |
            | W777725014012 | E0869VD0     | LOCATION_1 | DISCARDED | LOCATION_1          | America/New_York    | true       | 5               |                                                        | ADDITIVE_SOLUTION_ISSUES |                   |                           |                                  |                  |               |             |

        When I request "<Unit Number>" in the "LOCATION_1"
        Then I receive the following:
            | Unit Number   | Product Code   | Temperature Category   | Location   | Collection Location   | Collection TimeZone   | Volumes   | RESPONSE ERROR   | Found It   | Storage Location   | Device Stored   | Properties   |
            | <Unit Number> | <Product Code> | <Temperature Category> | <Location> | <Collection Location> | <Collection TimeZone> | <Volumes> | <RESPONSE ERROR> | <Found It> | <Storage Location> | <Device Stored> | <Properties> |

        Examples:
            | Unit Number   | Product Code | Temperature Category | Location   | Volumes                          | Collection Location | Collection TimeZone | RESPONSE ERROR                                   | Found It | Storage Location | Device Stored | Properties  |
            | W777725014012 | E0869V00     | FROZEN               | LOCATION_1 | Anticoagulant - 50, Volume - 500 | LOCATION_1          | America/New_York    |                                                  | Yes      | Freezer 1        | MDL SHELF 100 | COMPLETED=Y |
            | W777725014012 | E0869VA0     | FROZEN               | LOCATION_2 |                                  | LOCATION_2          | America/Los_Angeles | INVENTORY_NOT_FOUND_IN_LOCATION                  | Yes      | Freezer 2        |               |             |
            | W777725014012 | E0869VB0     | FROZEN               | LOCATION_1 |                                  | LOCATION_2          | America/Los_Angeles | INVENTORY_IS_QUARANTINED, INVENTORY_IS_UNLABELED | Yes      | Refrigerator 1   | MDL SHELF 100 |             |
            | W777725014012 | E0869VC0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    | INVENTORY_IS_EXPIRED                             | Yes      | Refrigerator 2   |               |             |
            | W777725014012 | E0869VD0     | FROZEN               | LOCATION_1 |                                  | LOCATION_1          | America/New_York    |                                                  | False    |                  |               |             |



