--delete exisist customers
delete from order_service.lk_customer_address where customer_id in ( select id from order_service.lk_customer where code in ('A1235','B2346','C3457','D4568','E5679','032BCOLMa','0122105a','006B3FVALa','007000065a'));

delete from order_service.lk_customer where code in ('A1235','B2346','C3457','D4568','E5679','032BCOLMa','0122105a','006B3FVALa','007000065a');

INSERT INTO order_service.lk_customer (EXTERNAL_ID, CUSTOMER_TYPE, NAME, CODE, DEPARTMENT_CODE, DEPARTMENT_NAME, FOREIGN_FLAG, PHONE_NUMBER, ACTIVE, create_date, modification_date) VALUES ('A1235', '1', 'Creative Testing Solutions', 'A1235', NULL, NULL, 'N', NULL, 'TRUE', current_date, current_date);
INSERT INTO order_service.lk_customer (EXTERNAL_ID, CUSTOMER_TYPE, NAME, CODE, DEPARTMENT_CODE, DEPARTMENT_NAME, FOREIGN_FLAG, PHONE_NUMBER, ACTIVE, create_date, modification_date) VALUES ('B2346', '1', 'Advanced Medical Center', 'B2346', NULL, NULL, 'N', NULL, 'TRUE', current_date, current_date);
INSERT INTO order_service.lk_customer (EXTERNAL_ID, CUSTOMER_TYPE, NAME, CODE, DEPARTMENT_CODE, DEPARTMENT_NAME, FOREIGN_FLAG, PHONE_NUMBER, ACTIVE, create_date, modification_date) VALUES ('C3457', '1', 'Pioneer Health Services', 'C3457', NULL, NULL, 'N', NULL, 'TRUE', current_date, current_date);
INSERT INTO order_service.lk_customer (EXTERNAL_ID, CUSTOMER_TYPE, NAME, CODE, DEPARTMENT_CODE, DEPARTMENT_NAME, FOREIGN_FLAG, PHONE_NUMBER, ACTIVE, create_date, modification_date) VALUES ('D4568', '1', 'Sunrise Health Clinic', 'D4568', NULL, NULL, 'N', NULL, 'TRUE', current_date, current_date);
INSERT INTO order_service.lk_customer (EXTERNAL_ID, CUSTOMER_TYPE, NAME, CODE, DEPARTMENT_CODE, DEPARTMENT_NAME, FOREIGN_FLAG, PHONE_NUMBER, ACTIVE, create_date, modification_date) VALUES ('E5679', '1', 'Harmony Medical Group', 'E5679', NULL, NULL, 'N', NULL, 'TRUE', current_date, current_date);
INSERT INTO order_service.lk_customer (EXTERNAL_ID, CUSTOMER_TYPE, NAME, CODE, DEPARTMENT_CODE, DEPARTMENT_NAME, FOREIGN_FLAG, PHONE_NUMBER, ACTIVE, create_date, modification_date) VALUES ('032BCOLMa', '1', 'Columbus Community Hospital', '032BCOLMa', NULL, NULL, 'N', NULL, 'TRUE', current_date, current_date);
INSERT INTO order_service.lk_customer (EXTERNAL_ID, CUSTOMER_TYPE, NAME, CODE, DEPARTMENT_CODE, DEPARTMENT_NAME, FOREIGN_FLAG, PHONE_NUMBER, ACTIVE, create_date, modification_date) VALUES ('0122105a', '1', 'Caldwell Memorial Hospital- ARC', '0122105a', NULL, NULL, 'N', NULL, 'TRUE', current_date, current_date);
INSERT INTO order_service.lk_customer (EXTERNAL_ID, CUSTOMER_TYPE, NAME, CODE, DEPARTMENT_CODE, DEPARTMENT_NAME, FOREIGN_FLAG, PHONE_NUMBER, ACTIVE, create_date, modification_date) VALUES ('006B3FVALa', '1', 'UCI Health - Fountain Valley', '006B3FVALa', NULL, NULL, 'N', NULL, 'TRUE', current_date, current_date);
INSERT INTO order_service.lk_customer (EXTERNAL_ID, CUSTOMER_TYPE, NAME, CODE, DEPARTMENT_CODE, DEPARTMENT_NAME, FOREIGN_FLAG, PHONE_NUMBER, ACTIVE, create_date, modification_date) VALUES ('007000065a', '1', 'MT Grahm Regional Medical Center', '007000065a', NULL, NULL, 'N', NULL, 'TRUE', current_date, current_date);

INSERT INTO order_service.lk_customer_address (customer_id, address_type, CONTACT_NAME, state, postal_code, country, COUNTRY_CODE, city, DISTRICT, ADDRESS_LINE1, ADDRESS_LINE2, ACTIVE, create_date, modification_date)
SELECT (SELECT id FROM order_service.lk_customer WHERE external_id = 'A1235'), 'SHIPPING', NULL, 'VA', '20152', 'USA', '1', 'Chantilly', NULL, '123 Main street, APT 1', NULL, 'TRUE', current_date, current_date;
INSERT INTO order_service.lk_customer_address (customer_id, address_type, CONTACT_NAME, state, postal_code, country, COUNTRY_CODE, city, DISTRICT, ADDRESS_LINE1, ADDRESS_LINE2, ACTIVE, create_date, modification_date)
SELECT (SELECT id FROM order_service.lk_customer WHERE external_id = 'B2346'), 'SHIPPING', NULL, 'CA', '90210', 'USA', '1', 'Beverly Hills', NULL, '456 Elm Street, Suite 200', NULL, 'TRUE', current_date, current_date;
INSERT INTO order_service.lk_customer_address (customer_id, address_type, CONTACT_NAME, state, postal_code, country, COUNTRY_CODE, city, DISTRICT, ADDRESS_LINE1, ADDRESS_LINE2, ACTIVE, create_date, modification_date)
SELECT (SELECT id FROM order_service.lk_customer WHERE external_id = 'C3457'), 'SHIPPING', NULL, 'TX', '73301', 'USA', '1', 'Austin', NULL, '1234 Pine Street, Building A', NULL, 'TRUE', current_date, current_date;
INSERT INTO order_service.lk_customer_address (customer_id, address_type, CONTACT_NAME, state, postal_code, country, COUNTRY_CODE, city, DISTRICT, ADDRESS_LINE1, ADDRESS_LINE2, ACTIVE, create_date, modification_date)
SELECT (SELECT id FROM order_service.lk_customer WHERE external_id = 'D4568'), 'SHIPPING', NULL, 'FL', '33101', 'USA', '1', 'Miami', NULL, '9101 Sunset Boulevard, Suite 500', NULL, 'TRUE', current_date, current_date;
INSERT INTO order_service.lk_customer_address (customer_id, address_type, CONTACT_NAME, state, postal_code, country, COUNTRY_CODE, city, DISTRICT, ADDRESS_LINE1, ADDRESS_LINE2, ACTIVE, create_date, modification_date)
SELECT (SELECT id FROM order_service.lk_customer WHERE external_id = 'E5679'), 'SHIPPING', NULL, 'NY', '10001', 'USA', '1', 'New York', NULL, '123 Broadway, Suite 400', NULL, 'TRUE', current_date, current_date;
INSERT INTO order_service.lk_customer_address (customer_id, address_type, CONTACT_NAME, state, postal_code, country, COUNTRY_CODE, city, DISTRICT, ADDRESS_LINE1, ADDRESS_LINE2, ACTIVE, create_date, modification_date)
SELECT (SELECT id FROM order_service.lk_customer WHERE external_id = '032BCOLMa'), 'SHIPPING', NULL, 'WI', '53925', 'USA', '1', 'Columbus', NULL, '1515 Park Avenue', NULL, 'TRUE', current_date, current_date;
INSERT INTO order_service.lk_customer_address (customer_id, address_type, CONTACT_NAME, state, postal_code, country, COUNTRY_CODE, city, DISTRICT, ADDRESS_LINE1, ADDRESS_LINE2, ACTIVE, create_date, modification_date)
SELECT (SELECT id FROM order_service.lk_customer WHERE external_id = '0122105a'), 'SHIPPING', NULL, 'NC', '28645', 'USA', '1', 'Lenoir', NULL, '321 Mulberry Street SW', NULL, 'TRUE', current_date, current_date;
INSERT INTO order_service.lk_customer_address (customer_id, address_type, CONTACT_NAME, state, postal_code, country, COUNTRY_CODE, city, DISTRICT, ADDRESS_LINE1, ADDRESS_LINE2, ACTIVE, create_date, modification_date)
SELECT (SELECT id FROM order_service.lk_customer WHERE external_id = '006B3FVALa'), 'SHIPPING', NULL, 'CA', '92708', 'USA', '1', 'Fountain Valley', NULL, '17100 Euclid Avenue', NULL, 'TRUE', current_date, current_date;
INSERT INTO order_service.lk_customer_address (customer_id, address_type, CONTACT_NAME, state, postal_code, country, COUNTRY_CODE, city, DISTRICT, ADDRESS_LINE1, ADDRESS_LINE2, ACTIVE, create_date, modification_date)
SELECT (SELECT id FROM order_service.lk_customer WHERE external_id = '007000065a'), 'SHIPPING', NULL, 'AZ', '85546', 'USA', '1', 'Safford', NULL, '1600 S 20th Avenue', NULL, 'TRUE', current_date, current_date;
