# -*- mode: Python -*-

# Load the helm_remote extension so we can create services from remote Helm charts
load("ext://helm_remote", "helm_remote")

# Load the kim_build extension so we can build images using nerdctl
load('ext://nerdctl', 'nerdctl_build')

# Load the 'configmap' extension
load('ext://configmap', 'configmap_create')

# Load the namespace extension
load('ext://namespace', 'namespace_create', 'namespace_inject')


# Function to build and deploy: cert-manager
def cert_manager():
    # Specify the Kubernetes manifest for the deployment
    helm_remote(
        'cert-manager',
        repo_url='https://charts.jetstack.io',
        version='v1.14.5',
        set=[
            'installCRDs=true',  # Automatically install and manage CRDs as part of the Helm release
        ]
    )


def otel_operator():
    helm_remote(
        'opentelemetry-collector',
        repo_url='https://open-telemetry.github.io/opentelemetry-helm-charts',
        set=[
            'image.repository=otel/opentelemetry-collector-k8s',
            'mode=deployment',
            'dnsPolicy=ClusterFirstWithHostNet',
        ]
    )
    k8s_resource(
        'opentelemetry-collector',
        resource_deps=[
            'cert-manager-webhook',
            'cert-manager-cainjector',
            'cert-manager'
        ]
    )


# Function to build and deploy: keycloak service
def keycloak_service():
    # Specify the Kubernetes manifest for the deployment
    k8s_yaml([
        './src/main/k8s/id-namespace.yaml',
        './src/main/k8s/keycloak-service.yaml',
        './src/main/k8s/keycloak-deployment.yaml',
        './src/main/k8s/id-ingress.yaml'
    ])
    configmap_create(
        'keycloak-realm-config',
        namespace='id',
        from_file=['realm.json=./src/main/k8s/realm-config/biopro-realm.json']
    )
    k8s_resource(
        'keycloak-deployment',
        port_forwards=9080,
        links=['id.local.gd'],
        resource_deps=['cert-manager']
    )

# Function to build and deploy: redis service
def redis_service():
    # Specify the Kubernetes manifest for the deployment
    k8s_yaml([
        './src/main/k8s/caching-namespace.yaml',
        './src/main/k8s/redis-service.yaml',
        './src/main/k8s/redis-deployment.yaml',
    ])
    k8s_resource(
        'redis-deployment',
        port_forwards=6379,
        trigger_mode=TRIGGER_MODE_MANUAL
    )


def biopro_service():
    # Specify the Kubernetes manifest for the deployment
    nerdctl_build(
        'local/partner-order-provider-service',
        dockerfile='./src/main/docker/Dockerfile',
        context='.',
        ignore=['.git', 'src', '.idea'],
        live_update=[sync('./target/classes', '/app')]
    )
    k8s_yaml([
        './src/main/k8s/api-namespace.yaml',
        './src/main/k8s/biopro-deployment.yaml',
        './src/main/k8s/biopro-service.yaml',
        './src/main/k8s/api-ingress.yaml'
    ])
    k8s_resource(
        'partner-order-provider-service-deployment',
        links=['interface.local.gd'],
        resource_deps=[
            'keycloak-deployment',
            'redis-deployment',
            'opentelemetry-collector'
        ],
        trigger_mode=TRIGGER_MODE_MANUAL
    )


cert_manager()
otel_operator()
keycloak_service()
redis_service()
biopro_service()
