INSERT INTO irradiation.lk_configuration (key, value)
values ('OUT_OF_STORAGE_APHERESIS_PLATELETS_LEUKOREDUCED', '1440'),
       ('OUT_OF_STORAGE_PLASMA_TRANSFUSABLE', '30'),
       ('OUT_OF_STORAGE_PRT_APHERESIS_PLATELETS', '1440'),
       ('OUT_OF_STORAGE_RED_BLOOD_CELLS', '30'),
       ('OUT_OF_STORAGE_RED_BLOOD_CELLS_LEUKOREDUCED', '30'),
       ('OUT_OF_STORAGE_WHOLE_BLOOD', '30'),
       ('OUT_OF_STORAGE_WHOLE_BLOOD_LEUKOREDUCED', '30'),
       ('OUT_OF_STORAGE_WASHED_APHERESIS_PLATELETS', '1440'),
       ('OUT_OF_STORAGE_WASHED_PRT_APHERESIS_PLATELETS', '1440'),
       ('OUT_OF_STORAGE_WASHED_RED_BLOOD_CELLS', '30')
ON CONFLICT (key) DO NOTHING;