export interface PrintDto {
  file: string;
}

export type PrintType =
  | 'DONATION_PACKAGE'
  | 'EMERGENCY_EXCEPTIONAL_RELEASE'
  | 'TEST_RESULTS'
  | 'DONATION_QUARANTINE_REPORT'
  | 'ORDER_REPORT'
  | 'INTERNAL_TRANSFER_ORDER_REVIEW_REPORT'
  | 'ORDER_PACKING_SLIP'
  | 'ORDER_SHIPPING_LABEL'
  | 'FILL_ORDER_SHORT_DATE_PULL_LIST'
  | 'EXCEPTION_REPORTS'
  | 'APHERESIS_PLATELET_REPORT'
  | 'PRESCRIPTION_INFORMATION_REPORT'
  | 'ROGUE_UNIT_REPORT'
  | 'LOOKBACK_REPORT'
  | 'EARLY_DONATION_REPORT'
  | 'DONATION_REVIEW_REPORT'
  | 'DUPLICATE_DONOR_REPORT'
  | 'DHQ_DEFERRED_DONOR_REPORT'
  | 'EVENT_MANAGEMENT_EXPORT'
  | 'CASE_SUMMARY'
  | 'EVENT_MANAGEMENT_DETAIL_EXPORT'
  | 'ARBOVIRUS_CASE_DETAIL'
  | 'SAMPLING_PLAN_PROGRESS_REPORT'
  | 'DEVICE_LIST_REPORT'
  | 'DEVICE_HISTORY'
  | 'SPECIALTY_LAB_REVIEW_REPORT'
  | 'SAMPLING_PLAN_EVALUATION_MODE_REPORT'
  | 'PP_BACTERIAL_SAMPLE_TIME_REPORT'
  | 'POOLED_PLATELETS_WORKLOAD_REPORT'
  | 'SPECIALTY_LAB_DISCREPANCY_REPORT'
  | 'EMPLOYEE_SEARCH'
  | 'ROLE_SEARCH'
  | 'ROLE_DETAILS'
  | 'USER_SEARCH'
  | 'USER_DETAILS'
  | 'INTERNAL_TRANSFER_ORDER_PACKING_SLIP'
  | 'DONOR_ADDRESS_CORRECTION_REPORT'
  | 'TEST_RESULT_DISCREPANCY_REPORT';

export type PrintExtesion = 'docx' | 'pdf' | 'xlsx';

export const ORDER_PRINT_TYPE = 'ORDER_REPORT';
export const INTERNAL_TRANSFER_ORDER_REVIEW_REPORT_PRINT_TYPE = 'INTERNAL_TRANSFER_ORDER_REVIEW_REPORT';
export const PDF_EXTENSION = 'pdf';
export const DOCX_EXTENSION = 'docx';
export const XLSX_EXTENSION = 'xlsx';

export const ORDER_PACKING_SLIP = 'ORDER_PACKING_SLIP';
export const INTERNAL_TRANSFER_ORDER_PACKING_SLIP = 'INTERNAL_TRANSFER_ORDER_PACKING_SLIP';
export const ORDER_SHIPPING_LABEL = 'ORDER_SHIPPING_LABEL';
export const FILL_ORDER_SHORT_DATE_PULL_LIST = 'FILL_ORDER_SHORT_DATE_PULL_LIST';
export const DONATION_QUARANTINE_REPORT = 'DONATION_QUARANTINE_REPORT';
export const APHERESIS_PLATELET_REPORT = 'APHERESIS_PLATELET_REPORT';
export const ROGUE_UNIT_REPORT_ORDER_PRINT_TYPE = 'ROGUE_UNIT_REPORT';
export const EVENT_MANAGEMENT_EXPORT = 'EVENT_MANAGEMENT_EXPORT';
export const EVENT_MANAGEMENT_DETAIL_EXPORT = 'EVENT_MANAGEMENT_DETAIL_EXPORT';
export const DEVICE_LIST_REPORT = 'DEVICE_LIST_REPORT';
export const DEVICE_HISTORY = 'DEVICE_HISTORY';
export const PP_BACTERIAL_SAMPLE_TIME_REPORT = 'PP_BACTERIAL_SAMPLE_TIME_REPORT';
export const PP_WORKLOAD_REPORT = 'POOLED_PLATELETS_WORKLOAD_REPORT';
export const USER_SEARCH = 'USER_SEARCH';
export const USER_DETAILS = 'USER_DETAILS';
export const ROLE_SEARCH = 'ROLE_SEARCH';
export const ROLE_DETAILS = 'ROLE_DETAILS';
export const INTERNAL_SHIPMENT_TYPE = 'INTERNAL';
export const DONOR_ADDRESS_CORRECTION_REPORT = 'DONOR_ADDRESS_CORRECTION_REPORT';
export const TEST_RESULT_DISCREPANCY_REPORT = 'TEST_RESULT_DISCREPANCY_REPORT';
