package com.arcone.biopro.distribution.order.infrastructure.mapper;

import com.arcone.biopro.distribution.order.domain.model.Order;
import com.arcone.biopro.distribution.order.domain.repository.LocationRepository;
import com.arcone.biopro.distribution.order.domain.service.CustomerService;
import com.arcone.biopro.distribution.order.domain.service.LookupService;
import com.arcone.biopro.distribution.order.domain.service.OrderConfigService;
import com.arcone.biopro.distribution.order.infrastructure.persistence.OrderEntity;
import com.arcone.biopro.distribution.order.infrastructure.persistence.OrderItemEntity;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Collections;
import java.util.List;

import static java.util.Optional.ofNullable;

@Component
@RequiredArgsConstructor
public class OrderEntityMapper {

    private final CustomerService customerService;
    private final LookupService lookupService;
    private final OrderConfigService orderConfigService;
    private static final String DATE_TIME_FORMAT = "yyyy-MM-dd HH:mm:ss";
    private final LocationRepository locationRepository;

    public OrderEntity mapToEntity(final Order order) {
        return OrderEntity.builder()
            .id(order.getId())
            .orderNumber(order.getOrderNumber().getOrderNumber())
            .externalId(order.getOrderExternalId().getOrderExternalId())
            .locationCode(order.getLocationFrom().getCode())
            .shipmentType(order.getShipmentType().getShipmentType())
            .shippingMethod(order.getShippingMethod().getShippingMethod())
            .shippingCustomerName( order.getShippingCustomer() != null ? order.getShippingCustomer().getName() : null)
            .shippingCustomerCode(order.getShippingCustomer() != null ? order.getShippingCustomer().getCode() : null)
            .billingCustomerName(order.getBillingCustomer() != null ? order.getBillingCustomer().getName() : null)
            .billingCustomerCode(order.getBillingCustomer() != null ? order.getBillingCustomer().getCode() : null)
            .desiredShippingDate(order.getDesiredShippingDate())
            .willCallPickup(order.getWillCallPickup())
            .phoneNumber(order.getPhoneNumber())
            .productCategory(order.getProductCategory().getProductCategory())
            .comments(order.getComments())
            .status(order.getOrderStatus().getOrderStatus())
            .priority(order.getOrderPriority().getPriority())
            .deliveryType(order.getOrderPriority().getDeliveryType())
            .createEmployeeId(order.getCreateEmployeeId())
            .createDate(order.getCreateDate())
            .modificationDate(order.getModificationDate())
            .deleteDate(order.getDeleteDate())
            .completeComments(order.getCompleteComments())
            .completeEmployeeId(order.getCompleteEmployeeId())
            .completeDate(order.getCompleteDate())
            .backOrder(order.isBackOrder())
            .cancelDate(order.getCancelDate())
            .cancelEmployeeId(order.getCancelEmployeeId())
            .cancelReason(order.getCancelReason())
            .modifyByProcess(order.getModifiedByProcess())
            .modifyEmployeeId(order.getModifyEmployeeId())
            .modifyReason(order.getModifyReason())
            .transactionId(order.getTransactionId())
            .quarantinedProducts(order.getQuarantinedProducts())
            .labelStatus(order.getLabelStatus() != null ? order.getLabelStatus().value() : null)
            .build();
    }

    public Order mapToDomain(final OrderEntity orderEntity, final List<OrderItemEntity> orderItemEntities) {
        var order = new Order(
            this.customerService,
            this.lookupService,
            orderEntity.getId(),
            // TODO FIX - find a way to get autogenerated value from database.
            orderEntity.getId(),
            orderEntity.getExternalId(),
            orderEntity.getLocationCode(),
            orderEntity.getShipmentType(),
            orderEntity.getShippingMethod(),
            orderEntity.getShippingCustomerCode(),
            orderEntity.getBillingCustomerCode(),
            ofNullable(orderEntity.getDesiredShippingDate()).map(LocalDate::toString).orElse(null),
            orderEntity.getWillCallPickup(),
            orderEntity.getPhoneNumber(),
            orderEntity.getProductCategory(),
            orderEntity.getComments(),
            orderEntity.getStatus(),
            orderEntity.getDeliveryType(),
            orderEntity.getCreateEmployeeId(),
            ofNullable(orderEntity.getCreateDate()).map(dateTime -> DateTimeFormatter.ofPattern(DATE_TIME_FORMAT).format(dateTime)).orElse(null),
            orderEntity.getModificationDate(),
            orderEntity.getDeleteDate(),
            orderEntity.getQuarantinedProducts(),
            orderEntity.getLabelStatus(),
            locationRepository
        );

        ofNullable(orderItemEntities)
            .filter(orderItems -> !orderItems.isEmpty())
            .orElseGet(Collections::emptyList)
            .forEach(orderItemEntity -> order.addItem(orderItemEntity.getId()
                    , orderItemEntity.getProductFamily(), orderItemEntity.getBloodType()
                    , orderItemEntity.getQuantity(),orderItemEntity.getQuantityShipped(), orderItemEntity.getComments(), orderItemEntity.getCreateDate()
                    , orderItemEntity.getModificationDate(), this.orderConfigService
                )
            );

        order.setCompleteComments(orderEntity.getCompleteComments());
        order.setCompleteEmployeeId(orderEntity.getCompleteEmployeeId());
        order.setCompleteDate(orderEntity.getCompleteDate());
        order.setBackOrder(orderEntity.getBackOrder());
        order.setCancelDate(orderEntity.getCancelDate());
        order.setCancelReason(orderEntity.getCancelReason());
        order.setCancelEmployeeId(orderEntity.getCancelEmployeeId());
        order.setModifyEmployeeId(orderEntity.getModifyEmployeeId());
        order.setModifyReason(orderEntity.getModifyReason());
        order.setModifiedByProcess(orderEntity.getModifyByProcess());
        order.setTransactionId(orderEntity.getTransactionId());

        return order;
    }

}
