{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "interface-exception-collector.fullname" . }}-migration
  labels:
    {{- include "interface-exception-collector.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "interface-exception-collector.fullname" . }}-migration
      labels:
        {{- include "interface-exception-collector.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "interface-exception-collector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migration
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - java
            - -jar
            - /app/app.jar
            - --spring.profiles.active=migration
            - --spring.flyway.enabled=true
            - --spring.jpa.hibernate.ddl-auto=none
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ include "interface-exception-collector.databaseHost" . }}:{{ .Values.app.database.port }}/{{ .Values.app.database.name }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.app.database.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "interface-exception-collector.databaseSecretName" . }}
                  key: {{ if .Values.postgresql.enabled }}postgres-password{{ else }}password{{ end }}
            - name: SPRING_FLYWAY_ENABLED
              value: "true"
            - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
            - name: SPRING_FLYWAY_LOCATIONS
              value: "classpath:db/migration"
          resources:
            {{- toYaml .Values.migration.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 3
{{- end }}