apiVersion: v2
name: interface-exception-collector
description: A Helm chart for Interface Exception Collector Service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - exception-collector
  - microservice
  - kafka
  - postgresql
home: https://github.com/arcone/interface-exception-collector
sources:
  - https://github.com/arcone/interface-exception-collector
maintainers:
  - name: BioPro Team
    email: biopro-team@arcone.com
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
annotations:
  category: Microservice