import {
  CalendarDripicons,
  CancelSecRsa,
  ChevronDownDripicons,
  ChevronDownHeroiconsSolid,
  ChevronLeftDripicons,
  ChevronRightHeroiconsSolid,
  ClipboardListHeroiconsOutline,
  ClockHeroiconsOutline,
  DialogConfirmationRsa,
  DownloadHeroiconsOutline,
  IconDefinition,
  IconPdfRsa,
  IconWordRsa,
  IconXlsRsa,
  PatientRecordRsa,
  PendingRsa,
  PlusCircleHeroiconsSolid,
  PlusHeroiconsSolid,
  PrinterHeroiconsOutline,
  ProductPlasmaRsa,
  ProductPlateletsRsa,
  ProductRbcRsa,
  ProductWholeBloodRsa,
  SubmitSecRsa,
  ThumbUpHeroiconsOutline,
  ToDoDripicons,
  TrashHeroiconsOutline,
  TrashHeroiconsSolid,
  WarningDripicons,
  XCircleHeroiconsOutline,
  XHeroiconsOutline,
} from '@rsa/theme';

export const RSA_ICONS = [
  PendingRsa,
  ProductWholeBloodRsa,
  ProductPlateletsRsa,
  ProductPlasmaRsa,
  ProductRbcRsa,
  CancelSecRsa,
  SubmitSecRsa,
  IconPdfRsa,
  IconXlsRsa,
  IconWordRsa,
  PatientRecordRsa,
  DialogConfirmationRsa,
];

export const HEROIC_ICONS = [
  XHeroiconsOutline,
  ChevronRightHeroiconsSolid,
  ChevronDownHeroiconsSolid,
  PlusHeroiconsSolid,
  ClipboardListHeroiconsOutline,
  ThumbUpHeroiconsOutline,
  TrashHeroiconsOutline,
  PlusCircleHeroiconsSolid,
  ClockHeroiconsOutline,
  TrashHeroiconsSolid,
  XCircleHeroiconsOutline,
  ToDoDripicons,
  DownloadHeroiconsOutline,
  PrinterHeroiconsOutline,
];

export const DRIP_ICONS = [
  WarningDripicons,
  ChevronDownDripicons,
  ChevronLeftDripicons,
  CalendarDripicons,
  TrashHeroiconsOutline,
  PlusCircleHeroiconsSolid,
];

export const allDistributionIcons: IconDefinition[] = [...RSA_ICONS, ...HEROIC_ICONS, ...DRIP_ICONS];
